# -*- coding: utf-8 -*-
"""weeks 4_5 delivarable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTOtN1CaqOA1nC4qjGc3oZtPsEb-q6LW
"""

import pandas as pd

sold = pd.read_csv("sold_enriched_with_rates.csv")
listing = pd.read_csv("listing_enriched_with_rates.csv")

sold.shape

listing.shape

#change fields to datetime format
sold["CloseDate"] = pd.to_datetime(sold["CloseDate"])
sold["PurchaseContractDate"] = pd.to_datetime(sold["PurchaseContractDate"])
sold["ListingContractDate"] = pd.to_datetime(sold["ListingContractDate"])
sold["ContractStatusChangeDate"] = pd.to_datetime(sold["ContractStatusChangeDate"])

print(sold["CloseDate"].dtypes)
print(sold["PurchaseContractDate"].dtypes)
print(sold["ListingContractDate"].dtypes)
print(sold["ContractStatusChangeDate"].dtypes)

listing["CloseDate"] = pd.to_datetime(listing["CloseDate"])
listing["PurchaseContractDate"] = pd.to_datetime(listing["PurchaseContractDate"])
listing["ListingContractDate"] = pd.to_datetime(listing["ListingContractDate"])
listing["ContractStatusChangeDate"] = pd.to_datetime(listing["ContractStatusChangeDate"])

print(listing["CloseDate"].dtypes)
print(listing["PurchaseContractDate"].dtypes)
print(listing["ListingContractDate"].dtypes)
print(listing["ContractStatusChangeDate"].dtypes)

#handle missing values
sold_missing = sold.isnull().mean()*100
sold_missing[sold_missing>0].sort_values(ascending=False)

sold=sold.drop(columns=["WaterfrontYN","BasementYN"])

listing_missing = listing.isnull().mean()*100
listing_missing[listing_missing>0].sort_values(ascending=False)


#ensure numeric fields are properly typed
numeric_cols = ["ClosePrice","ListPrice","OriginalListPrice",
                "LivingArea","LotSizeAcres","BedroomsTotal",
                "BathroomsTotalInteger","DaysOnMarket"]
for col in numeric_cols:
    if col in listing.columns:
        listing[col]=pd.to_numeric(listing[col],errors="coerce")
    if col in sold.columns:
        sold[col]=pd.to_numeric(sold[col],errors="coerce")

#remove/flag invalid numbers
listing["invalid_nums"] = (
    (listing["ClosePrice"]<=0) | (listing["LivingArea"]<=0) |
    (listing["DaysOnMarket"]<0) | (listing["BedroomsTotal"]<0) |
    (listing["BathroomsTotalInteger"]<0)
)

listing["invalid_nums"].sum()

sold["invalid_nums"] = (
    (sold["ClosePrice"]<=0) | (sold["LivingArea"]<=0) |
    (sold["DaysOnMarket"]<0) | (sold["BedroomsTotal"]<0) |
    (sold["BathroomsTotalInteger"]<0)
)

sold["invalid_nums"].sum()


#data consistency checks
sold["listing_after_close_flag"] = (sold["ListingContractDate"]>sold["CloseDate"])
sold["purchase_after_close_flag"] = (sold["PurchaseContractDate"]>sold["CloseDate"])
sold["negative_timeline_flag"] = (sold["PurchaseContractDate"]<sold["ListingContractDate"])
sold[["listing_after_close_flag","purchase_after_close_flag","negative_timeline_flag"]].sum()

listing["listing_after_close_flag"] = (listing["ListingContractDate"]>listing["CloseDate"])
listing["purchase_after_close_flag"] = (listing["PurchaseContractDate"]>listing["CloseDate"])
listing["negative_timeline_flag"] = (listing["PurchaseContractDate"]<listing["ListingContractDate"])
listing[["listing_after_close_flag","purchase_after_close_flag","negative_timeline_flag"]].sum()


#Geographic Data checks
sold["missing_coord_flag"] = (sold["Latitude"].isna()|sold["Longitude"].isna())
sold["missing_coord_flag"].sum()

listing["missing_coord_flag"] = (listing["Latitude"].isna()|listing["Longitude"].isna())
listing["missing_coord_flag"].sum()

sold["zero_coord_flag"] = (sold["Latitude"]==0) | (sold["Longitude"]==0)
print(sold["zero_coord_flag"].sum())

listing["zero_coord_flag"] = (listing["Latitude"]==0) | (listing["Longitude"]==0)
print(listing["zero_coord_flag"].sum())

sold["positive_long_flag"] = sold["Longitude"]>0
print(sold["positive_long_flag"].sum())

listing["positive_long_flag"] = listing["Longitude"]>0
print(listing["positive_long_flag"].sum())

sold["implausible_coord_flag"] = (
    (sold["Latitude"]<32) | (sold["Latitude"]>42) |
    (sold["Longitude"]<-125) | (sold["Longitude"]>-115)
)

print(sold["implausible_coord_flag"].sum())

listing["implausible_coord_flag"] = (
    (listing["Latitude"]<32) | (listing["Latitude"]>42) |
    (listing["Longitude"]<-125) | (listing["Longitude"]>-115)
)

print(listing["implausible_coord_flag"].sum())

#save CSVs
sold.to_csv("sold_cleaned_flagged.csv", index=False)
listing.to_csv("listing_cleaned_flagged.csv", index=False)